# Form implementation generated from reading ui file '.\files\gui.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FC(object):
    def setupUi(self, FC):
        FC.setObjectName("FC")
        FC.resize(1240, 791)
        FC.setMinimumSize(QtCore.QSize(1240, 791))
        FC.setMaximumSize(QtCore.QSize(1240, 791))
        FC.setStyleSheet("/*Copyright (c) DevSec Studio. All rights reserved.\n"
"\n"
"MIT License\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
"*/\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    background-color: #3a3a3a;\n"
"    color: #fff;\n"
"    selection-background-color: #b78620;\n"
"    selection-color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar \n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 57, 57, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item \n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected \n"
"{\n"
"    background-color: rgba(183, 134, 32, 20%);\n"
"    border: 1px solid #b78620;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed \n"
"{\n"
"    background-color: rgb(183, 134, 32);\n"
"    border: 1px solid #b78620;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 57, 57, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    border: 1px solid #222;\n"
"    padding: 4px;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::separator\n"
"{\n"
"       background-color: rgb(183, 134, 32);\n"
"    height: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #555;\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: rgba(183, 134, 32, 20%);\n"
"    border: 1px solid #b78620;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolBar-----*/\n"
"QToolBar\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(69, 69, 69, 255),stop:1 rgba(58, 58, 58, 255));\n"
"    border-top: none;\n"
"    border-bottom: 1px solid #4f4f4f;\n"
"    border-left: 1px solid #4f4f4f;\n"
"    border-right: 1px solid #4f4f4f;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolBar::separator\n"
"{\n"
"    background-color: #2e2e2e;\n"
"    width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton \n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    padding: 5px;\n"
"    padding-left: 8px;\n"
"    padding-right: 8px;\n"
"    margin-left: 1px;\n"
"}\n"
"\n"
"\n"
"QToolButton:hover\n"
"{\n"
"    background-color: rgba(183, 134, 32, 20%);\n"
"    border: 1px solid #b78620;\n"
"    color: #fff;\n"
"    \n"
"}\n"
"\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 57, 57, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    border: 1px solid #b78620;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:checked\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 57, 57, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    border: 1px solid #222;\n"
"}\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(84, 84, 84, 255),stop:1 rgba(59, 59, 59, 255));\n"
"    color: #ffffff;\n"
"    min-width: 80px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::flat\n"
"{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgba(183, 134, 32, 20%);\n"
"    border: 1px solid #b78620;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(74, 74, 74, 255),stop:1 rgba(49, 49, 49, 255));\n"
"    border: 1px solid #b78620;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::checked\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(74, 74, 74, 255),stop:1 rgba(49, 49, 49, 255));\n"
"    border: 1px solid #222;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit\n"
"{\n"
"    background-color: #131313;\n"
"    color : #eee;\n"
"    border: 1px solid #343434;\n"
"    border-radius: 2px;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QPlainTExtEdit-----*/\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #131313;\n"
"    color : #eee;\n"
"    border: 1px solid #343434;\n"
"    border-radius: 2px;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTabBar-----*/\n"
"QTabBar::tab\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(84, 84, 84, 255),stop:1 rgba(59, 59, 59, 255));\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: #666;\n"
"    border-bottom: none;\n"
"    padding: 5px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabWidget::pane \n"
"{\n"
"    background-color: red;\n"
"    border: 1px solid #666;\n"
"    top: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; \n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
"    background-color: #0c0c0d;\n"
"    margin-left: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    background-color: #0c0c0d;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    margin-bottom: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    border-top-color: #b78620;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QComboBox-----*/\n"
"QComboBox\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(84, 84, 84, 255),stop:1 rgba(59, 59, 59, 255));\n"
"    border: 1px solid #000;\n"
"    padding-left: 6px;\n"
"    color: #ffffff;\n"
"    height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    background-color: #b78620;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    background-color: #383838;\n"
"    color: #ffffff;\n"
"    border: 1px solid black;\n"
"    selection-background-color: #b78620;\n"
"    outline: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 57, 57, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: black;\n"
"    border-left-style: solid; \n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"}\n"
"\n"
"\n"
"/*-----QSpinBox & QDateTimeEdit-----*/\n"
"QSpinBox,\n"
"QDateTimeEdit \n"
"{\n"
"    background-color: #131313;\n"
"    color : #eee;\n"
"    border: 1px solid #343434;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    border-radius : 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button, \n"
"QDateTimeEdit::up-button\n"
"{\n"
"    border-top-right-radius:2px;\n"
"    background-color: #777777;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:hover, \n"
"QDateTimeEdit::up-button:hover\n"
"{\n"
"    background-color: #585858;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:pressed, \n"
"QDateTimeEdit::up-button:pressed\n"
"{\n"
"    background-color: #252525;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-arrow,\n"
"QDateTimeEdit::up-arrow\n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 7px;\n"
"    height: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-button, \n"
"QDateTimeEdit::down-button\n"
"{\n"
"    border-bottom-right-radius:2px;\n"
"    background-color: #777777;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-button:hover, \n"
"QDateTimeEdit::down-button:hover\n"
"{\n"
"    background-color: #585858;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-button:pressed, \n"
"QDateTimeEdit::down-button:pressed\n"
"{\n"
"    background-color: #252525;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-arrow,\n"
"QDateTimeEdit::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 7px;\n"
"    height: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QGroupBox-----*/\n"
"QGroupBox \n"
"{\n"
"    border: 1px solid;\n"
"    border-color: #666666;\n"
"    border-radius: 5px;\n"
"    margin-top: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox::title  \n"
"{\n"
"    background-color: transparent;\n"
"    color: #eee;\n"
"    subcontrol-origin: margin;\n"
"    padding: 5px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QHeaderView-----*/\n"
"QHeaderView::section\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(60, 60, 60, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"    text-align: left;\n"
"    padding: 4px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QHeaderView::section:disabled\n"
"{\n"
"    background-color: #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(60, 60, 60, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"QHeaderView::section::vertical::only-one\n"
"{\n"
"    border-top: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"{\n"
"    border-top: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"QHeaderView::section::horizontal::only-one\n"
"{\n"
"    border-left: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"{\n"
"    border-left: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(60, 60, 60, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeWidget-----*/\n"
"QTreeView\n"
"{\n"
"    show-decoration-selected: 1;\n"
"    alternate-background-color: #3a3a3a;\n"
"    selection-color: #fff;\n"
"    background-color: #2d2d2d;\n"
"    border: 1px solid gray;\n"
"    padding-top : 5px;\n"
"    color: #fff;\n"
"    font: 8pt;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"    color:#fff;\n"
"    background-color: #b78620;\n"
"    border-radius: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:!selected:hover\n"
"{\n"
"    background-color: #262626;\n"
"    border: none;\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings \n"
"{\n"
"    image: url(://tree-closed.png);\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  \n"
"{\n"
"    image: url(://tree-open.png);\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QListView-----*/\n"
"QListView \n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(83, 83, 83, 255),stop:0.293269 rgba(81, 81, 81, 255),stop:0.634615 rgba(79, 79, 79, 255),stop:1 rgba(83, 83, 83, 255));\n"
"    border : none;\n"
"    color: white;\n"
"    show-decoration-selected: 1; \n"
"    outline: 0;\n"
"    border: 1px solid gray;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::disabled \n"
"{\n"
"    background-color: #656565;\n"
"    color: #1b1b1b;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item \n"
"{\n"
"    background-color: #2d2d2d;\n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:alternate \n"
"{\n"
"    background-color: #3a3a3a;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected \n"
"{\n"
"    background-color: #b78620;\n"
"    border: 1px solid #b78620;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected:!active \n"
"{\n"
"    background-color: #b78620;\n"
"    border: 1px solid #b78620;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected:active \n"
"{\n"
"    background-color: #b78620;\n"
"    border: 1px solid #b78620;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:hover {\n"
"    background-color: #262626;\n"
"    border: none;\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"QCheckBox\n"
"{\n"
"    background-color: transparent;\n"
"    color: lightgray;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    background-color: #323232;\n"
"    border: 1px solid darkgray;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(\"./ressources/check.png\");\n"
"    background-color: #b78620;\n"
"    border: 1px solid #3a546e;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #b78620; \n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QRadioButton-----*/\n"
"QRadioButton \n"
"{\n"
"    color: lightgray;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked:hover \n"
"{\n"
"    background-color: lightgray;\n"
"    border: 2px solid #b78620;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked \n"
"{\n"
"    border: 2px solid #b78620;\n"
"    border-radius: 6px;\n"
"    background-color: rgba(183,134,32,20%);  \n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QSlider-----*/\n"
"QSlider::groove:horizontal \n"
"{\n"
"    background-color: transparent;\n"
"    height: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal \n"
"{\n"
"    background-color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal \n"
"{\n"
"    background-color: #131313;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background-color: #fff;\n"
"    width: 14px;\n"
"    margin-top: -6px;\n"
"    margin-bottom: -6px;\n"
"    border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:hover \n"
"{\n"
"    background-color: #fff;\n"
"    border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled \n"
"{\n"
"    background-color: #bbb;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal:disabled \n"
"{\n"
"    background-color: #fff;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:disabled \n"
"{\n"
"    background-color: #fff;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal\n"
"{\n"
"    border: 1px solid #222222;\n"
"    background-color: #3d3d3d;\n"
"    height: 15px;\n"
"    margin: 0px 16px 0 16px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(97, 97, 97, 255),stop:1 rgba(90, 90, 90, 255));\n"
"    border: 1px solid #2d2d2d;\n"
"    min-height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(97, 97, 97, 255),stop:1 rgba(90, 90, 90, 255));\n"
"    border: 1px solid #2d2d2d;\n"
"    width: 15px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(97, 97, 97, 255),stop:1 rgba(90, 90, 90, 255));\n"
"    border: 1px solid #2d2d2d;\n"
"    width: 15px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::right-arrow:horizontal\n"
"{\n"
"    image: url(://arrow-right.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::left-arrow:horizontal\n"
"{\n"
"    image: url(://arrow-left.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    background-color: #3d3d3d;\n"
"    width: 16px;\n"
"    border: 1px solid #2d2d2d;\n"
"    margin: 16px 0px 16px 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(97, 97, 97, 255),stop:1 rgba(90, 90, 90, 255));\n"
"    border: 1px solid #2d2d2d;\n"
"    min-height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(97, 97, 97, 255),stop:1 rgba(90, 90, 90, 255));\n"
"    border: 1px solid #2d2d2d;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(97, 97, 97, 255),stop:1 rgba(90, 90, 90, 255));\n"
"    border: 1px solid #2d2d2d;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:vertical\n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::down-arrow:vertical\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"    background: none;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QProgressBar-----*/\n"
"QProgressBar\n"
"{\n"
"    border: 1px solid #666666;\n"
"    text-align: center;\n"
"    color: #000;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #b78620;\n"
"    width: 30px;\n"
"    margin: 0.5px;\n"
"\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(FC)
        self.centralwidget.setObjectName("centralwidget")
        self.deviceFrame = QtWidgets.QGroupBox(self.centralwidget)
        self.deviceFrame.setGeometry(QtCore.QRect(260, -10, 971, 161))
        self.deviceFrame.setTitle("")
        self.deviceFrame.setObjectName("deviceFrame")
        self.portTitle = QtWidgets.QLabel(self.deviceFrame)
        self.portTitle.setGeometry(QtCore.QRect(20, 45, 91, 21))
        self.portTitle.setObjectName("portTitle")
        self.portSelectionBox = QtWidgets.QComboBox(self.deviceFrame)
        self.portSelectionBox.setGeometry(QtCore.QRect(90, 40, 151, 31))
        self.portSelectionBox.setCurrentText("")
        self.portSelectionBox.setObjectName("portSelectionBox")
        self.terminalBox = QtWidgets.QTextEdit(self.deviceFrame)
        self.terminalBox.setGeometry(QtCore.QRect(260, 30, 421, 121))
        self.terminalBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.terminalBox.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.terminalBox.setObjectName("terminalBox")
        self.deviceModes = QtWidgets.QGroupBox(self.deviceFrame)
        self.deviceModes.setGeometry(QtCore.QRect(690, 10, 121, 141))
        self.deviceModes.setTitle("")
        self.deviceModes.setObjectName("deviceModes")
        self.RXCheckBox = QtWidgets.QCheckBox(self.deviceModes)
        self.RXCheckBox.setGeometry(QtCore.QRect(10, 90, 101, 20))
        self.RXCheckBox.setStyleSheet("QCheckBox::indicator:checked\n"
"{\n"
"    background-color: #ff0000;\n"
"    border: 1px solid #3a546e;\n"
"}")
        self.RXCheckBox.setChecked(True)
        self.RXCheckBox.setObjectName("RXCheckBox")
        self.IDLECheckBox = QtWidgets.QCheckBox(self.deviceModes)
        self.IDLECheckBox.setGeometry(QtCore.QRect(10, 70, 82, 20))
        self.IDLECheckBox.setStyleSheet("QCheckBox::indicator:checked\n"
"{\n"
"    background-color: #45f248;\n"
"    border: 1px solid #3a546e;\n"
"}")
        self.IDLECheckBox.setCheckable(True)
        self.IDLECheckBox.setChecked(True)
        self.IDLECheckBox.setObjectName("IDLECheckBox")
        self.INITCheckBox = QtWidgets.QCheckBox(self.deviceModes)
        self.INITCheckBox.setGeometry(QtCore.QRect(10, 50, 121, 20))
        self.INITCheckBox.setStyleSheet("QCheckBox::indicator:checked\n"
"{\n"
"    background-color: #4fa7ff;\n"
"    border: 1px solid #3a546e;\n"
"}")
        self.INITCheckBox.setChecked(True)
        self.INITCheckBox.setObjectName("INITCheckBox")
        self.deviceModeTitle = QtWidgets.QLabel(self.deviceModes)
        self.deviceModeTitle.setGeometry(QtCore.QRect(10, 25, 101, 16))
        self.deviceModeTitle.setObjectName("deviceModeTitle")
        self.TXCheckBox = QtWidgets.QCheckBox(self.deviceModes)
        self.TXCheckBox.setGeometry(QtCore.QRect(10, 110, 121, 20))
        self.TXCheckBox.setStyleSheet("QCheckBox::indicator:checked\n"
"{\n"
"    background-color: #ff0000;\n"
"    border: 1px solid #3a546e;\n"
"}")
        self.TXCheckBox.setChecked(True)
        self.TXCheckBox.setObjectName("TXCheckBox")
        self.initializeModule = QtWidgets.QPushButton(self.deviceFrame)
        self.initializeModule.setGeometry(QtCore.QRect(20, 120, 221, 31))
        self.initializeModule.setObjectName("initializeModule")
        self.baudSelectionBox = QtWidgets.QComboBox(self.deviceFrame)
        self.baudSelectionBox.setGeometry(QtCore.QRect(90, 80, 151, 31))
        self.baudSelectionBox.setCurrentText("")
        self.baudSelectionBox.setObjectName("baudSelectionBox")
        self.portTitle_2 = QtWidgets.QLabel(self.deviceFrame)
        self.portTitle_2.setGeometry(QtCore.QRect(20, 85, 91, 21))
        self.portTitle_2.setObjectName("portTitle_2")
        self.bufferInfoBox = QtWidgets.QGroupBox(self.deviceFrame)
        self.bufferInfoBox.setGeometry(QtCore.QRect(820, 10, 141, 141))
        self.bufferInfoBox.setTitle("")
        self.bufferInfoBox.setObjectName("bufferInfoBox")
        self.rx_buffer = QtWidgets.QLineEdit(self.bufferInfoBox)
        self.rx_buffer.setEnabled(False)
        self.rx_buffer.setGeometry(QtCore.QRect(40, 57, 81, 21))
        self.rx_buffer.setFrame(True)
        self.rx_buffer.setObjectName("rx_buffer")
        self.tx_buffer = QtWidgets.QLineEdit(self.bufferInfoBox)
        self.tx_buffer.setEnabled(False)
        self.tx_buffer.setGeometry(QtCore.QRect(40, 81, 81, 21))
        self.tx_buffer.setObjectName("tx_buffer")
        self.rx_buffe_title = QtWidgets.QLabel(self.bufferInfoBox)
        self.rx_buffe_title.setGeometry(QtCore.QRect(10, 52, 49, 31))
        self.rx_buffe_title.setObjectName("rx_buffe_title")
        self.tx_buffer_title = QtWidgets.QLabel(self.bufferInfoBox)
        self.tx_buffer_title.setGeometry(QtCore.QRect(10, 76, 49, 31))
        self.tx_buffer_title.setObjectName("tx_buffer_title")
        self.latencyArayuz = QtWidgets.QLineEdit(self.bufferInfoBox)
        self.latencyArayuz.setEnabled(False)
        self.latencyArayuz.setGeometry(QtCore.QRect(40, 105, 81, 21))
        self.latencyArayuz.setObjectName("latencyArayuz")
        self.latencyArayuzTitle = QtWidgets.QLabel(self.bufferInfoBox)
        self.latencyArayuzTitle.setGeometry(QtCore.QRect(10, 100, 49, 31))
        self.latencyArayuzTitle.setObjectName("latencyArayuzTitle")
        self.deviceModeTitle_2 = QtWidgets.QLabel(self.bufferInfoBox)
        self.deviceModeTitle_2.setGeometry(QtCore.QRect(10, 25, 81, 16))
        self.deviceModeTitle_2.setObjectName("deviceModeTitle_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 130, 1221, 651))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777211))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 250, 871, 361))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.angleGraph = PlotWidget(self.groupBox_2)
        self.angleGraph.setGeometry(QtCore.QRect(15, 40, 841, 301))
        self.angleGraph.setObjectName("angleGraph")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(720, 290, 111, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/emirp/.designer/backup/angle_graph_info.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(580, 40, 301, 221))
        self.groupBox_3.setStyleSheet("/*-----QSlider-----*/\n"
"QSlider::groove:horizontal \n"
"{\n"
"    background-color: transparent;\n"
"    height: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal \n"
"{\n"
"    background-color: #b78620;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal \n"
"{\n"
"    background-color: #131313;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background-color: #b78620;\n"
"    width: 14px;\n"
"    margin-top: -6px;\n"
"    margin-bottom: -6px;\n"
"    border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:hover \n"
"{\n"
"    background-color: #d89e25;\n"
"    border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled \n"
"{\n"
"    background-color: #bbb;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 3px;\n"
"\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.esc_1 = QtWidgets.QSlider(self.groupBox_3)
        self.esc_1.setGeometry(QtCore.QRect(80, 70, 22, 111))
        self.esc_1.setStyleSheet("QSlider::handle:vertical \n"
"{\n"
"    background-color: #404040;\n"
"    border: 1px solid #000;\n"
"    height: 12px;\n"
"    margin-left: -6px;\n"
"    margin-right: -6px;\n"
"\n"
"}")
        self.esc_1.setMaximum(999)
        self.esc_1.setProperty("value", 0)
        self.esc_1.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.esc_1.setObjectName("esc_1")
        self.total_esc = QtWidgets.QSlider(self.groupBox_3)
        self.total_esc.setGeometry(QtCore.QRect(20, 70, 22, 111))
        self.total_esc.setStyleSheet("QSlider::handle:vertical \n"
"{\n"
"    background-color: #404040;\n"
"    border: 1px solid #000;\n"
"    height: 12px;\n"
"    margin-left: -6px;\n"
"    margin-right: -6px;\n"
"\n"
"}")
        self.total_esc.setMaximum(999)
        self.total_esc.setProperty("value", 0)
        self.total_esc.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.total_esc.setObjectName("total_esc")
        self.esc_2 = QtWidgets.QSlider(self.groupBox_3)
        self.esc_2.setGeometry(QtCore.QRect(140, 70, 22, 111))
        self.esc_2.setStyleSheet("QSlider::handle:vertical \n"
"{\n"
"    background-color: #404040;\n"
"    border: 1px solid #000;\n"
"    height: 12px;\n"
"    margin-left: -6px;\n"
"    margin-right: -6px;\n"
"\n"
"}")
        self.esc_2.setMaximum(999)
        self.esc_2.setProperty("value", 0)
        self.esc_2.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.esc_2.setObjectName("esc_2")
        self.total_esc_lcd = QtWidgets.QLCDNumber(self.groupBox_3)
        self.total_esc_lcd.setGeometry(QtCore.QRect(10, 30, 41, 31))
        self.total_esc_lcd.setDigitCount(3)
        self.total_esc_lcd.setProperty("intValue", 0)
        self.total_esc_lcd.setObjectName("total_esc_lcd")
        self.esc_1_lcd = QtWidgets.QLCDNumber(self.groupBox_3)
        self.esc_1_lcd.setGeometry(QtCore.QRect(70, 30, 41, 31))
        self.esc_1_lcd.setDigitCount(3)
        self.esc_1_lcd.setProperty("intValue", 0)
        self.esc_1_lcd.setObjectName("esc_1_lcd")
        self.esc_2_lcd = QtWidgets.QLCDNumber(self.groupBox_3)
        self.esc_2_lcd.setGeometry(QtCore.QRect(130, 30, 41, 31))
        self.esc_2_lcd.setDigitCount(3)
        self.esc_2_lcd.setProperty("intValue", 0)
        self.esc_2_lcd.setObjectName("esc_2_lcd")
        self.esc_3 = QtWidgets.QSlider(self.groupBox_3)
        self.esc_3.setGeometry(QtCore.QRect(200, 70, 22, 111))
        self.esc_3.setStyleSheet("QSlider::handle:vertical \n"
"{\n"
"    background-color: #404040;\n"
"    border: 1px solid #000;\n"
"    height: 12px;\n"
"    margin-left: -6px;\n"
"    margin-right: -6px;\n"
"\n"
"}")
        self.esc_3.setMaximum(999)
        self.esc_3.setProperty("value", 0)
        self.esc_3.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.esc_3.setObjectName("esc_3")
        self.esc_3_lcd = QtWidgets.QLCDNumber(self.groupBox_3)
        self.esc_3_lcd.setGeometry(QtCore.QRect(190, 30, 41, 31))
        self.esc_3_lcd.setDigitCount(3)
        self.esc_3_lcd.setProperty("intValue", 0)
        self.esc_3_lcd.setObjectName("esc_3_lcd")
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setGeometry(QtCore.QRect(54, 21, 16, 199))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setGeometry(QtCore.QRect(115, 21, 16, 199))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.groupBox_3)
        self.line_3.setGeometry(QtCore.QRect(174, 21, 16, 199))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.total_esc_text = QtWidgets.QLabel(self.groupBox_3)
        self.total_esc_text.setGeometry(QtCore.QRect(15, 190, 41, 16))
        self.total_esc_text.setObjectName("total_esc_text")
        self.esc_1_text = QtWidgets.QLabel(self.groupBox_3)
        self.esc_1_text.setGeometry(QtCore.QRect(77, 190, 41, 16))
        self.esc_1_text.setObjectName("esc_1_text")
        self.esc_2_text = QtWidgets.QLabel(self.groupBox_3)
        self.esc_2_text.setGeometry(QtCore.QRect(137, 190, 41, 16))
        self.esc_2_text.setObjectName("esc_2_text")
        self.esc_3_text = QtWidgets.QLabel(self.groupBox_3)
        self.esc_3_text.setGeometry(QtCore.QRect(196, 190, 41, 16))
        self.esc_3_text.setObjectName("esc_3_text")
        self.line_4 = QtWidgets.QFrame(self.groupBox_3)
        self.line_4.setGeometry(QtCore.QRect(231, 21, 16, 199))
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.esc_4_text = QtWidgets.QLabel(self.groupBox_3)
        self.esc_4_text.setGeometry(QtCore.QRect(254, 190, 31, 16))
        self.esc_4_text.setObjectName("esc_4_text")
        self.esc_4_lcd = QtWidgets.QLCDNumber(self.groupBox_3)
        self.esc_4_lcd.setGeometry(QtCore.QRect(250, 30, 41, 31))
        self.esc_4_lcd.setDigitCount(3)
        self.esc_4_lcd.setProperty("intValue", 0)
        self.esc_4_lcd.setObjectName("esc_4_lcd")
        self.esc_4 = QtWidgets.QSlider(self.groupBox_3)
        self.esc_4.setGeometry(QtCore.QRect(260, 70, 22, 111))
        self.esc_4.setStyleSheet("QSlider::handle:vertical \n"
"{\n"
"    background-color: #404040;\n"
"    border: 1px solid #000;\n"
"    height: 12px;\n"
"    margin-left: -6px;\n"
"    margin-right: -6px;\n"
"\n"
"}")
        self.esc_4.setMaximum(999)
        self.esc_4.setProperty("value", 0)
        self.esc_4.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.esc_4.setObjectName("esc_4")
        self.esc_1.raise_()
        self.total_esc.raise_()
        self.esc_2.raise_()
        self.esc_3.raise_()
        self.line.raise_()
        self.total_esc_lcd.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.esc_3_lcd.raise_()
        self.esc_1_lcd.raise_()
        self.esc_2_lcd.raise_()
        self.total_esc_text.raise_()
        self.esc_1_text.raise_()
        self.esc_2_text.raise_()
        self.esc_3_text.raise_()
        self.line_4.raise_()
        self.esc_4_text.raise_()
        self.esc_4_lcd.raise_()
        self.esc_4.raise_()
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 40, 561, 221))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.hiz_title = QtWidgets.QLabel(self.groupBox_4)
        self.hiz_title.setGeometry(QtCore.QRect(67, 29, 41, 21))
        self.hiz_title.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.hiz_title.setObjectName("hiz_title")
        self.hiz_text_4 = QtWidgets.QLabel(self.groupBox_4)
        self.hiz_text_4.setEnabled(False)
        self.hiz_text_4.setGeometry(QtCore.QRect(140, 95, 91, 31))
        self.hiz_text_4.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 15pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.hiz_text_4.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.hiz_text_4.setScaledContents(False)
        self.hiz_text_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.hiz_text_4.setObjectName("hiz_text_4")
        self.hiz_text_2 = QtWidgets.QLabel(self.groupBox_4)
        self.hiz_text_2.setEnabled(False)
        self.hiz_text_2.setGeometry(QtCore.QRect(40, 95, 91, 31))
        self.hiz_text_2.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 15pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.hiz_text_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.hiz_text_2.setScaledContents(False)
        self.hiz_text_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.hiz_text_2.setObjectName("hiz_text_2")
        self.hiz_title_3 = QtWidgets.QLabel(self.groupBox_4)
        self.hiz_title_3.setGeometry(QtCore.QRect(20, 60, 16, 21))
        self.hiz_title_3.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.hiz_title_3.setObjectName("hiz_title_3")
        self.hiz_title_4 = QtWidgets.QLabel(self.groupBox_4)
        self.hiz_title_4.setGeometry(QtCore.QRect(20, 100, 16, 21))
        self.hiz_title_4.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.hiz_title_4.setObjectName("hiz_title_4")
        self.hiz_text_6 = QtWidgets.QLabel(self.groupBox_4)
        self.hiz_text_6.setEnabled(False)
        self.hiz_text_6.setGeometry(QtCore.QRect(140, 55, 91, 31))
        self.hiz_text_6.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 15pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.hiz_text_6.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.hiz_text_6.setScaledContents(False)
        self.hiz_text_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.hiz_text_6.setObjectName("hiz_text_6")
        self.hiz_title_5 = QtWidgets.QLabel(self.groupBox_4)
        self.hiz_title_5.setGeometry(QtCore.QRect(20, 140, 16, 21))
        self.hiz_title_5.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.hiz_title_5.setObjectName("hiz_title_5")
        self.hiz_text_5 = QtWidgets.QLabel(self.groupBox_4)
        self.hiz_text_5.setEnabled(False)
        self.hiz_text_5.setGeometry(QtCore.QRect(140, 135, 91, 31))
        self.hiz_text_5.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 15pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.hiz_text_5.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.hiz_text_5.setScaledContents(False)
        self.hiz_text_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.hiz_text_5.setObjectName("hiz_text_5")
        self.hiz_text_3 = QtWidgets.QLabel(self.groupBox_4)
        self.hiz_text_3.setEnabled(False)
        self.hiz_text_3.setGeometry(QtCore.QRect(40, 135, 91, 31))
        self.hiz_text_3.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 15pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.hiz_text_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.hiz_text_3.setScaledContents(False)
        self.hiz_text_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.hiz_text_3.setObjectName("hiz_text_3")
        self.hiz_text = QtWidgets.QLabel(self.groupBox_4)
        self.hiz_text.setEnabled(False)
        self.hiz_text.setGeometry(QtCore.QRect(40, 55, 91, 31))
        self.hiz_text.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 15pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.hiz_text.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.hiz_text.setScaledContents(False)
        self.hiz_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.hiz_text.setObjectName("hiz_text")
        self.hiz_title_2 = QtWidgets.QLabel(self.groupBox_4)
        self.hiz_title_2.setGeometry(QtCore.QRect(169, 29, 41, 21))
        self.hiz_title_2.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.hiz_title_2.setObjectName("hiz_title_2")
        self.pid_get_values_button = QtWidgets.QPushButton(self.groupBox_4)
        self.pid_get_values_button.setGeometry(QtCore.QRect(40, 175, 191, 31))
        self.pid_get_values_button.setObjectName("pid_get_values_button")
        self.pid_configurate_button = QtWidgets.QPushButton(self.groupBox_4)
        self.pid_configurate_button.setGeometry(QtCore.QRect(240, 175, 92, 31))
        self.pid_configurate_button.setObjectName("pid_configurate_button")
        self.pid_p_slider = QtWidgets.QSlider(self.groupBox_4)
        self.pid_p_slider.setGeometry(QtCore.QRect(250, 60, 291, 22))
        self.pid_p_slider.setMaximum(300)
        self.pid_p_slider.setProperty("value", 61)
        self.pid_p_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.pid_p_slider.setObjectName("pid_p_slider")
        self.pid_i_slider = QtWidgets.QSlider(self.groupBox_4)
        self.pid_i_slider.setGeometry(QtCore.QRect(250, 100, 291, 22))
        self.pid_i_slider.setMaximum(100)
        self.pid_i_slider.setProperty("value", 18)
        self.pid_i_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.pid_i_slider.setObjectName("pid_i_slider")
        self.pid_d_slider = QtWidgets.QSlider(self.groupBox_4)
        self.pid_d_slider.setGeometry(QtCore.QRect(250, 140, 291, 22))
        self.pid_d_slider.setMaximum(200)
        self.pid_d_slider.setProperty("value", 100)
        self.pid_d_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.pid_d_slider.setObjectName("pid_d_slider")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(250, 50, 49, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(536, 50, 49, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(250, 90, 49, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(517, 90, 49, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(250, 130, 49, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(524, 130, 49, 16))
        self.label_7.setObjectName("label_7")
        self.pid_lock_unlock_button = QtWidgets.QPushButton(self.groupBox_4)
        self.pid_lock_unlock_button.setGeometry(QtCore.QRect(340, 175, 92, 31))
        self.pid_lock_unlock_button.setObjectName("pid_lock_unlock_button")
        self.calibrate_esc_button = QtWidgets.QPushButton(self.groupBox_4)
        self.calibrate_esc_button.setGeometry(QtCore.QRect(440, 175, 101, 31))
        self.calibrate_esc_button.setObjectName("calibrate_esc_button")
        self.sensor_verileri_title_27 = QtWidgets.QLabel(self.tab)
        self.sensor_verileri_title_27.setGeometry(QtCore.QRect(210, 10, 181, 41))
        self.sensor_verileri_title_27.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 15pt;\n"
"    font-weight: bold;\n"
"}")
        self.sensor_verileri_title_27.setObjectName("sensor_verileri_title_27")
        self.sensor_verileri_title_28 = QtWidgets.QLabel(self.tab)
        self.sensor_verileri_title_28.setGeometry(QtCore.QRect(630, 10, 211, 41))
        self.sensor_verileri_title_28.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 15pt;\n"
"    font-weight: bold;\n"
"}")
        self.sensor_verileri_title_28.setObjectName("sensor_verileri_title_28")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(890, 40, 321, 571))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.z1_6 = QtWidgets.QLabel(self.groupBox_5)
        self.z1_6.setEnabled(False)
        self.z1_6.setGeometry(QtCore.QRect(160, 60, 137, 41))
        self.z1_6.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.z1_6.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.z1_6.setText("")
        self.z1_6.setScaledContents(False)
        self.z1_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.z1_6.setObjectName("z1_6")
        self.channel_5_title = QtWidgets.QLabel(self.groupBox_5)
        self.channel_5_title.setGeometry(QtCore.QRect(20, 473, 161, 21))
        self.channel_5_title.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.channel_5_title.setObjectName("channel_5_title")
        self.channel_2_text = QtWidgets.QLabel(self.groupBox_5)
        self.channel_2_text.setEnabled(False)
        self.channel_2_text.setGeometry(QtCore.QRect(20, 233, 141, 41))
        self.channel_2_text.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.channel_2_text.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.channel_2_text.setScaledContents(False)
        self.channel_2_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.channel_2_text.setObjectName("channel_2_text")
        self.channel_5_text = QtWidgets.QLabel(self.groupBox_5)
        self.channel_5_text.setEnabled(False)
        self.channel_5_text.setGeometry(QtCore.QRect(17, 500, 141, 41))
        self.channel_5_text.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.channel_5_text.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.channel_5_text.setScaledContents(False)
        self.channel_5_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.channel_5_text.setObjectName("channel_5_text")
        self.channel_1_title = QtWidgets.QLabel(self.groupBox_5)
        self.channel_1_title.setGeometry(QtCore.QRect(23, 116, 161, 21))
        self.channel_1_title.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.channel_1_title.setObjectName("channel_1_title")
        self.channel_1_plot = PlotWidget(self.groupBox_5)
        self.channel_1_plot.setEnabled(False)
        self.channel_1_plot.setGeometry(QtCore.QRect(163, 146, 131, 35))
        self.channel_1_plot.setObjectName("channel_1_plot")
        self.channel_4_plot = PlotWidget(self.groupBox_5)
        self.channel_4_plot.setEnabled(False)
        self.channel_4_plot.setGeometry(QtCore.QRect(163, 416, 131, 35))
        self.channel_4_plot.setObjectName("channel_4_plot")
        self.z1_2 = QtWidgets.QLabel(self.groupBox_5)
        self.z1_2.setEnabled(False)
        self.z1_2.setGeometry(QtCore.QRect(160, 413, 137, 41))
        self.z1_2.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.z1_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.z1_2.setText("")
        self.z1_2.setScaledContents(False)
        self.z1_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.z1_2.setObjectName("z1_2")
        self.channel_0_plot = PlotWidget(self.groupBox_5)
        self.channel_0_plot.setEnabled(False)
        self.channel_0_plot.setGeometry(QtCore.QRect(163, 63, 131, 35))
        self.channel_0_plot.setObjectName("channel_0_plot")
        self.channel_0_title = QtWidgets.QLabel(self.groupBox_5)
        self.channel_0_title.setGeometry(QtCore.QRect(23, 33, 161, 21))
        self.channel_0_title.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.channel_0_title.setObjectName("channel_0_title")
        self.channel_4_title = QtWidgets.QLabel(self.groupBox_5)
        self.channel_4_title.setGeometry(QtCore.QRect(23, 386, 161, 21))
        self.channel_4_title.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.channel_4_title.setObjectName("channel_4_title")
        self.channel_2_plot = PlotWidget(self.groupBox_5)
        self.channel_2_plot.setEnabled(False)
        self.channel_2_plot.setGeometry(QtCore.QRect(163, 236, 131, 35))
        self.channel_2_plot.setObjectName("channel_2_plot")
        self.channel_4_text = QtWidgets.QLabel(self.groupBox_5)
        self.channel_4_text.setEnabled(False)
        self.channel_4_text.setGeometry(QtCore.QRect(20, 413, 141, 41))
        self.channel_4_text.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.channel_4_text.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.channel_4_text.setScaledContents(False)
        self.channel_4_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.channel_4_text.setObjectName("channel_4_text")
        self.channel_0_text = QtWidgets.QLabel(self.groupBox_5)
        self.channel_0_text.setEnabled(False)
        self.channel_0_text.setGeometry(QtCore.QRect(20, 60, 141, 41))
        self.channel_0_text.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.channel_0_text.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.channel_0_text.setScaledContents(False)
        self.channel_0_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.channel_0_text.setObjectName("channel_0_text")
        self.channel_3_title = QtWidgets.QLabel(self.groupBox_5)
        self.channel_3_title.setGeometry(QtCore.QRect(23, 296, 161, 21))
        self.channel_3_title.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.channel_3_title.setObjectName("channel_3_title")
        self.z1 = QtWidgets.QLabel(self.groupBox_5)
        self.z1.setEnabled(False)
        self.z1.setGeometry(QtCore.QRect(157, 500, 137, 41))
        self.z1.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.z1.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.z1.setText("")
        self.z1.setScaledContents(False)
        self.z1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.z1.setObjectName("z1")
        self.channel_2_title = QtWidgets.QLabel(self.groupBox_5)
        self.channel_2_title.setGeometry(QtCore.QRect(23, 206, 161, 21))
        self.channel_2_title.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.channel_2_title.setObjectName("channel_2_title")
        self.channel_1_text = QtWidgets.QLabel(self.groupBox_5)
        self.channel_1_text.setEnabled(False)
        self.channel_1_text.setGeometry(QtCore.QRect(20, 143, 141, 41))
        self.channel_1_text.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.channel_1_text.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.channel_1_text.setScaledContents(False)
        self.channel_1_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.channel_1_text.setObjectName("channel_1_text")
        self.z1_4 = QtWidgets.QLabel(self.groupBox_5)
        self.z1_4.setEnabled(False)
        self.z1_4.setGeometry(QtCore.QRect(160, 233, 137, 41))
        self.z1_4.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.z1_4.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.z1_4.setText("")
        self.z1_4.setScaledContents(False)
        self.z1_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.z1_4.setObjectName("z1_4")
        self.channel_3_plot = PlotWidget(self.groupBox_5)
        self.channel_3_plot.setEnabled(False)
        self.channel_3_plot.setGeometry(QtCore.QRect(163, 326, 131, 35))
        self.channel_3_plot.setObjectName("channel_3_plot")
        self.channel_5_plot = PlotWidget(self.groupBox_5)
        self.channel_5_plot.setEnabled(False)
        self.channel_5_plot.setGeometry(QtCore.QRect(160, 503, 131, 35))
        self.channel_5_plot.setObjectName("channel_5_plot")
        self.channel_3_text = QtWidgets.QLabel(self.groupBox_5)
        self.channel_3_text.setEnabled(False)
        self.channel_3_text.setGeometry(QtCore.QRect(20, 323, 141, 41))
        self.channel_3_text.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.channel_3_text.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.channel_3_text.setScaledContents(False)
        self.channel_3_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.channel_3_text.setObjectName("channel_3_text")
        self.z1_3 = QtWidgets.QLabel(self.groupBox_5)
        self.z1_3.setEnabled(False)
        self.z1_3.setGeometry(QtCore.QRect(160, 323, 137, 41))
        self.z1_3.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.z1_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.z1_3.setText("")
        self.z1_3.setScaledContents(False)
        self.z1_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.z1_3.setObjectName("z1_3")
        self.z1_5 = QtWidgets.QLabel(self.groupBox_5)
        self.z1_5.setEnabled(False)
        self.z1_5.setGeometry(QtCore.QRect(160, 143, 137, 41))
        self.z1_5.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 20pt;\n"
"\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}")
        self.z1_5.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.z1_5.setText("")
        self.z1_5.setScaledContents(False)
        self.z1_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.z1_5.setObjectName("z1_5")
        self.sensor_verileri_title_29 = QtWidgets.QLabel(self.tab)
        self.sensor_verileri_title_29.setGeometry(QtCore.QRect(960, 10, 211, 41))
        self.sensor_verileri_title_29.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    font-style: normal;\n"
"    font-size: 15pt;\n"
"    font-weight: bold;\n"
"}")
        self.sensor_verileri_title_29.setObjectName("sensor_verileri_title_29")
        self.tabWidget.addTab(self.tab, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(10, -10, 1201, 621))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setGeometry(QtCore.QRect(610, 30, 581, 581))
        self.widget_2.setObjectName("widget_2")
        self.tabWidget.addTab(self.widget, "")
        self.arm_button = QtWidgets.QPushButton(self.centralwidget)
        self.arm_button.setGeometry(QtCore.QRect(10, 10, 116, 51))
        self.arm_button.setObjectName("arm_button")
        self.disarm_button = QtWidgets.QPushButton(self.centralwidget)
        self.disarm_button.setGeometry(QtCore.QRect(135, 10, 116, 51))
        self.disarm_button.setObjectName("disarm_button")
        self.debug_button = QtWidgets.QPushButton(self.centralwidget)
        self.debug_button.setEnabled(True)
        self.debug_button.setGeometry(QtCore.QRect(10, 70, 241, 51))
        self.debug_button.setObjectName("debug_button")
        FC.setCentralWidget(self.centralwidget)

        self.retranslateUi(FC)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FC)

    def retranslateUi(self, FC):
        _translate = QtCore.QCoreApplication.translate
        FC.setWindowTitle(_translate("FC", "Flight Controller Software"))
        self.portTitle.setText(_translate("FC", "COM Port :"))
        self.portSelectionBox.setPlaceholderText(_translate("FC", "--- Ports ---"))
        self.terminalBox.setHtml(_translate("FC", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.RXCheckBox.setText(_translate("FC", "RECEIVING"))
        self.IDLECheckBox.setText(_translate("FC", "IDLE"))
        self.INITCheckBox.setText(_translate("FC", "INIT"))
        self.deviceModeTitle.setText(_translate("FC", "Telemetry Modes :"))
        self.TXCheckBox.setText(_translate("FC", "TRANSMITTING"))
        self.initializeModule.setText(_translate("FC", "Initialize The Module"))
        self.baudSelectionBox.setPlaceholderText(_translate("FC", "--- Rates ---"))
        self.portTitle_2.setText(_translate("FC", "Baud Rate :"))
        self.rx_buffer.setText(_translate("FC", "0"))
        self.tx_buffer.setText(_translate("FC", "0"))
        self.rx_buffe_title.setText(_translate("FC", "  RX"))
        self.tx_buffer_title.setText(_translate("FC", "  TX"))
        self.latencyArayuz.setText(_translate("FC", "0"))
        self.latencyArayuzTitle.setText(_translate("FC", "  MS"))
        self.deviceModeTitle_2.setText(_translate("FC", "Com Buffers :"))
        self.total_esc_text.setText(_translate("FC", "TOTAL"))
        self.esc_1_text.setText(_translate("FC", "ESC 1"))
        self.esc_2_text.setText(_translate("FC", "ESC 2"))
        self.esc_3_text.setText(_translate("FC", "ESC 3"))
        self.esc_4_text.setText(_translate("FC", "ESC 4"))
        self.hiz_title.setText(_translate("FC", "Pitch"))
        self.hiz_text_4.setText(_translate("FC", "0.00018"))
        self.hiz_text_2.setText(_translate("FC", "0.00018"))
        self.hiz_title_3.setText(_translate("FC", "P"))
        self.hiz_title_4.setText(_translate("FC", "I"))
        self.hiz_text_6.setText(_translate("FC", "0.61"))
        self.hiz_title_5.setText(_translate("FC", "D"))
        self.hiz_text_5.setText(_translate("FC", "100"))
        self.hiz_text_3.setText(_translate("FC", "100"))
        self.hiz_text.setText(_translate("FC", "0.61"))
        self.hiz_title_2.setText(_translate("FC", "Roll"))
        self.pid_get_values_button.setText(_translate("FC", "Get Values"))
        self.pid_configurate_button.setText(_translate("FC", "Configurate"))
        self.label_2.setText(_translate("FC", "0"))
        self.label_3.setText(_translate("FC", "3"))
        self.label_4.setText(_translate("FC", "0"))
        self.label_5.setText(_translate("FC", "0.001"))
        self.label_6.setText(_translate("FC", "0"))
        self.label_7.setText(_translate("FC", "200"))
        self.pid_lock_unlock_button.setText(_translate("FC", "Unlock"))
        self.calibrate_esc_button.setText(_translate("FC", "Calibrate ESC"))
        self.sensor_verileri_title_27.setText(_translate("FC", "PID Configurations"))
        self.sensor_verileri_title_28.setText(_translate("FC", "ESC Configurations"))
        self.channel_5_title.setText(_translate("FC", "Channel 5"))
        self.channel_2_text.setText(_translate("FC", "0"))
        self.channel_5_text.setText(_translate("FC", "0"))
        self.channel_1_title.setText(_translate("FC", "Channel 1"))
        self.channel_0_title.setText(_translate("FC", "Channel 0"))
        self.channel_4_title.setText(_translate("FC", "Channel 4"))
        self.channel_4_text.setText(_translate("FC", "0"))
        self.channel_0_text.setText(_translate("FC", "0"))
        self.channel_3_title.setText(_translate("FC", "Channel 3"))
        self.channel_2_title.setText(_translate("FC", "Channel 2"))
        self.channel_1_text.setText(_translate("FC", "0"))
        self.channel_3_text.setText(_translate("FC", "0"))
        self.sensor_verileri_title_29.setText(_translate("FC", "Receiver Channels"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("FC", "FC Configurations"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("FC", "Mission Planner"))
        self.arm_button.setText(_translate("FC", "ARM"))
        self.disarm_button.setText(_translate("FC", "DISARM"))
        self.debug_button.setText(_translate("FC", "DEBUG MODE"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FC = QtWidgets.QMainWindow()
    ui = Ui_FC()
    ui.setupUi(FC)
    FC.show()
    sys.exit(app.exec())
